import { Bot, Code2, FileSearch, MessageSquareText, Scale, ShieldAlert, ShieldCheck } from 'lucide-react';

const outputTypes = [
  { label: 'Incident RCA', detail: 'Operational analysis', Icon: FileSearch, color: '#3b82f6' },
  { label: 'Generated code', detail: 'Implementation output', Icon: Code2, color: '#22c55e' },
  { label: 'SOC investigation', detail: 'Security summary', Icon: ShieldAlert, color: '#ef4444' },
  { label: 'Support response', detail: 'Customer-facing answer', Icon: MessageSquareText, color: '#f59e0b' },
  { label: 'Compliance review', detail: 'Policy-sensitive output', Icon: Scale, color: '#8b5cf6' },
  { label: 'Multi-agent result', detail: 'Final agent consensus', Icon: Bot, color: '#14b8a6' },
];

export default function GeneralProductScope() {
  return (
    <div className="narrative-panel">
      <div className="max-w-4xl">
        <span className="panel-kicker">Product scope</span>
        <h3 className="panel-title">What the Confidence Engine validates</h3>
        <p className="text-lg leading-8 text-slate-200">
          AI Confidence Engine validates the trustworthiness of outputs generated by AI agents, LLMs,
          multi-agent systems, automation tools, and analytical systems — before those outputs are used
          to make decisions.
        </p>
        <p className="mt-4 text-base leading-7 text-slate-400">
          It answers one core question: <em className="text-slate-200">"Can this generated output be trusted
          before we act on it?"</em> The output can be an incident RCA, generated code, a security
          investigation, a customer response, a compliance analysis, or the final answer of a
          multi-agent workflow.
        </p>
      </div>

      <div className="scope-output-grid">
        {outputTypes.map(({ label, detail, Icon, color }) => (
          <article key={label} className="scope-output-card">
            <div
              className="scope-output-icon"
              style={{ color, background: `${color}16`, borderColor: `${color}38` }}
            >
              <Icon size={20} />
            </div>
            <div>
              <strong>{label}</strong>
              <span>{detail}</span>
            </div>
          </article>
        ))}
      </div>

      <div className="mt-8 flex items-start gap-3 rounded-lg border border-blue-500/25 bg-blue-500/5 px-4 py-3 text-sm text-blue-300">
        <ShieldCheck size={16} className="mt-0.5 flex-shrink-0" />
        <span>
          <strong>Product boundary:</strong> the Confidence Engine does not generate outputs — it evaluates
          outputs that already exist. Kubernetes RCA validation is only one possible use case, not the
          product itself.
        </span>
      </div>
    </div>
  );
}
