import { ArrowRight, Bot, Brain, FileOutput, ShieldCheck, UserCheck } from 'lucide-react';

const productFlow = [
  { label: 'Generated Output', Icon: FileOutput, color: '#9da7b3' },
  { label: 'Confidence Engine', Icon: ShieldCheck, color: '#2dd4bf' },
  { label: 'Trust Decision', Icon: UserCheck, color: '#3b82f6' },
  { label: 'Human Feedback', Icon: Bot, color: '#f59e0b' },
  { label: 'Adaptive Learning', Icon: Brain, color: '#8b5cf6' },
];

const mantra = [
  { who: 'External systems', verb: 'generate.' },
  { who: 'Confidence Engine', verb: 'evaluates.' },
  { who: 'Humans', verb: 'decide.' },
  { who: 'The platform', verb: 'learns.' },
];

export default function GeneralProductScope() {
  return (
    <div className="narrative-panel">
      <div className="max-w-4xl">
        <p className="text-lg leading-8 text-slate-200">
          AI Confidence Engine validates the trustworthiness of outputs generated by AI agents, LLMs,
          multi-agent systems, automation tools, and analytical systems — before those outputs are used
          to make decisions.
        </p>
        <p className="mt-4 text-base leading-7 text-slate-400">
          It answers one core question: <em className="text-slate-200">"Can this generated output be trusted
          before we act on it?"</em> The output can be an incident RCA, generated code, a security
          investigation, a customer response, a compliance analysis, or the final answer of a
          multi-agent workflow.
        </p>
      </div>

      <div className="pf-hero-mantra">
        {mantra.map((m) => (
          <div key={m.who} className="pf-mantra-card">
            <div className="who">{m.who}</div>
            <div className="verb">{m.verb}</div>
          </div>
        ))}
      </div>

      <div className="mt-8 grid gap-3 lg:grid-cols-[repeat(5,minmax(0,1fr))]">
        {productFlow.map(({ label, Icon, color }, index) => (
          <div key={label} className="flex items-center gap-3">
            <article className="flow-node">
              <div
                className="flow-icon"
                style={{ color, background: `${color}16`, borderColor: `${color}38` }}
              >
                <Icon size={20} />
              </div>
              <span>{label}</span>
            </article>
            {index < productFlow.length - 1 && (
              <ArrowRight className="hidden lg:block text-slate-600 flex-shrink-0" size={18} />
            )}
          </div>
        ))}
      </div>

      <div className="mt-8 flex items-start gap-3 rounded-lg border border-blue-500/25 bg-blue-500/5 px-4 py-3 text-sm text-blue-300">
        <ShieldCheck size={16} className="mt-0.5 flex-shrink-0" />
        <span>
          <strong>Product boundary:</strong> the Confidence Engine does not generate outputs — it evaluates
          outputs that already exist. Kubernetes RCA validation is only one possible use case, not the
          product itself.
        </span>
      </div>
    </div>
  );
}
