export interface SimulatorScenario {
  id: string;
  label: string;
  outputType: string;
  generatedOutput: string;
  context: string;
  evidence: Array<{ label: string; status: 'validated' | 'missing' | 'contradiction'; detail: string }>;
  checks: Array<{ label: string; value: number; detail: string }>;
  score: number;
  decision: 'Trusted' | 'Needs Human Review' | 'Low Confidence' | 'Unsafe / Blocked';
  riskLevel: 'Low' | 'Medium' | 'High' | 'Critical';
  missingEvidence: string[];
  recommendedAction: string;
}

export const simulatorScenarios: SimulatorScenario[] = [
  {
    id: 'kubernetes-rca',
    label: 'Kubernetes RCA',
    outputType: 'RCA generated by an AI agent',
    generatedOutput: 'Traffic drop caused by intentional service migration to nginx-frontend-v2.',
    context: 'Dynatrace problem shows zero traffic on old frontend service after a deployment event.',
    evidence: [
      { label: 'Deployment event', status: 'validated', detail: 'nginx-frontend-v2 deployed before traffic shift.' },
      { label: 'Traffic metrics', status: 'validated', detail: 'Old service at 0 rpm, v2 receiving normal traffic.' },
      { label: 'Error logs', status: 'validated', detail: 'No matching application errors.' },
      { label: 'Ownership approval', status: 'missing', detail: 'Migration owner not confirmed.' },
    ],
    checks: [
      { label: 'Evidence validation', value: 92, detail: 'Telemetry supports the RCA.' },
      { label: 'Contradiction detection', value: 8, detail: 'Low contradiction risk.' },
      { label: 'Completeness scoring', value: 84, detail: 'Ownership evidence still missing.' },
      { label: 'Pattern match', value: 94, detail: 'Matches canary/service migration pattern.' },
    ],
    score: 89,
    decision: 'Trusted',
    riskLevel: 'Low',
    missingEvidence: ['Migration owner confirmation'],
    recommendedAction: 'Validate migration ownership, then close as planned change if confirmed.',
  },
  {
    id: 'support-answer',
    label: 'Support response',
    outputType: 'AI-generated customer support answer',
    generatedOutput: 'Issue a full refund and keep the premium plan active for the next billing cycle.',
    context: 'Customer reports duplicate charge on an enterprise account.',
    evidence: [
      { label: 'Ticket history', status: 'validated', detail: 'Duplicate charge confirmed.' },
      { label: 'Refund policy', status: 'contradiction', detail: 'Plan retention requires approval.' },
      { label: 'Billing record', status: 'validated', detail: 'Customer is eligible for correction.' },
      { label: 'Retention approval', status: 'missing', detail: 'No approval found.' },
    ],
    checks: [
      { label: 'Evidence validation', value: 78, detail: 'Refund claim is supported.' },
      { label: 'Contradiction detection', value: 31, detail: 'Retention promise conflicts with policy.' },
      { label: 'Completeness scoring', value: 68, detail: 'Approval evidence missing.' },
      { label: 'Policy alignment', value: 61, detail: 'Needs billing owner review.' },
    ],
    score: 72,
    decision: 'Needs Human Review',
    riskLevel: 'Medium',
    missingEvidence: ['Retention exception approval'],
    recommendedAction: 'Route to billing owner before sending the response.',
  },
  {
    id: 'compliance',
    label: 'Compliance recommendation',
    outputType: 'AI-generated compliance recommendation',
    generatedOutput: 'Approve vendor onboarding because data residency requirements are satisfied.',
    context: 'Vendor stores customer metadata across multiple regions.',
    evidence: [
      { label: 'Policy clause', status: 'validated', detail: 'Data residency clause identified.' },
      { label: 'Vendor architecture', status: 'missing', detail: 'Current region map not attached.' },
      { label: 'Audit trail', status: 'missing', detail: 'No DPA exception approval.' },
      { label: 'Risk register', status: 'contradiction', detail: 'Open residency risk exists.' },
    ],
    checks: [
      { label: 'Evidence validation', value: 48, detail: 'Core claims lack source evidence.' },
      { label: 'Contradiction detection', value: 58, detail: 'Risk register conflicts with recommendation.' },
      { label: 'Completeness scoring', value: 44, detail: 'Critical documents missing.' },
      { label: 'Policy alignment', value: 39, detail: 'Approval would be unsafe.' },
    ],
    score: 38,
    decision: 'Unsafe / Blocked',
    riskLevel: 'Critical',
    missingEvidence: ['Vendor region map', 'DPA exception approval', 'Updated audit evidence'],
    recommendedAction: 'Block recommendation and request compliance review.',
  },
  {
    id: 'security',
    label: 'Security investigation',
    outputType: 'AI-generated SOC investigation',
    generatedOutput: 'Alert is a false positive caused by normal admin activity.',
    context: 'Privileged command executed on production host outside maintenance window.',
    evidence: [
      { label: 'SIEM event', status: 'validated', detail: 'Privileged command confirmed.' },
      { label: 'Admin ticket', status: 'missing', detail: 'No change ticket found.' },
      { label: 'Endpoint telemetry', status: 'contradiction', detail: 'Suspicious child process detected.' },
      { label: 'Threat intel', status: 'validated', detail: 'Command pattern appears in known technique.' },
    ],
    checks: [
      { label: 'Evidence validation', value: 55, detail: 'Some sources support investigation, not conclusion.' },
      { label: 'Contradiction detection', value: 64, detail: 'Endpoint telemetry conflicts with false-positive claim.' },
      { label: 'Completeness scoring', value: 52, detail: 'Change ticket missing.' },
      { label: 'Threat alignment', value: 71, detail: 'Pattern resembles known technique.' },
    ],
    score: 46,
    decision: 'Low Confidence',
    riskLevel: 'High',
    missingEvidence: ['Approved change ticket', 'Admin confirmation'],
    recommendedAction: 'Escalate to security analyst and keep alert open.',
  },
];
